# Site settings
title: Christopher P. Barnes
email: senrabc@gmail.com
description: " This is a place for my projects on the interwebs. Thx Github "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://senrabc.github.io" # the base hostname & protocol for your site
twitter_username: "@senrabc"
github_username:  "senrabc"

# Build settings
markdown: kramdown
